
services:

  postgres:
    image: postgres:16
    container_name: alumni_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2205
      POSTGRES_DB: alumni_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./alumni_backend

    container_name: alumni_backend

    restart: always

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:2205@postgres:5432/alumni_db
      MAIL_USERNAME: gunnysmartz@gmail.com
      MAIL_PASSWORD: usghrhvhwnagawgi
      MAIL_FROM: gunnysmartz@gmail.com
      MAIL_PORT: 587
      MAIL_SERVER: smtp.gmail.com

  frontend:
    build:
      context: ./frontend/alumniserver

    container_name: alumni_frontend

    restart: always

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  postgres_data: